MujocoPlugins:
  - type: mujoco_ros_control/MujocoRosControlPlugin
    hardware:
      type: franka_mujoco/FrankaHWSim
      control_period: 0.001
      # robot_namespace: $(arg ns)

  - type: mujoco_ros_sensors/MujocoRosSensorsPlugin